apiVersion: apps/v1
Run docker/login-action@v3
Logging into docker.io...
(node:2016) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Error: Error response from daemon: Get "https://registry-1.docker.io/v2/": unknown: malformed HTTP Authorization header

kind: Deployment
metadata:
  name: session17-python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: session17-python
  template:
    metadata:
      labels:
        app: session17-python
    spec:
      containers:
        - name: session17-python
          image: rjsins/python-webapp:__IMAGE_TAG__
          imagePullPolicy: Always           # pull from Docker Hub
          ports:
            - containerPort: 5001
